#!/bin/sh
set -eu

[ -n "${SYNOPKG_PKGVAR:-}" ] || exit 1

STATE_DIR="${SYNOPKG_PKGVAR}/state"
LOGFILE="${SYNOPKG_PKGVAR}/tattler.log"

umask 077
mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR"
touch "$LOGFILE"
chmod 600 "$LOGFILE"

exit 0
